// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/inscriptions": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retourne la liste paginée de toutes les inscriptions avec filtres optionnels",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Lister les inscriptions (admin)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filtrer par type de participation",
                        "name": "participation_type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filtrer par pays",
                        "name": "pays",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filtrer par statut de paiement",
                        "name": "payment_status",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Numéro de page (défaut: 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Nombre d'éléments par page (défaut: 10)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/congres-app_backend_pkg_utils.PaginatedResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/congres-app_backend_internal_models.Inscription"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/congres-app_backend_pkg_utils.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/congres-app_backend_pkg_utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/inscriptions/export/csv": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Exporte la liste des inscriptions au format CSV avec filtres optionnels",
                "produces": [
                    "text/csv"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Exporter les inscriptions en CSV",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filtrer par type de participation",
                        "name": "participation_type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filtrer par pays",
                        "name": "pays",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filtrer par statut de paiement",
                        "name": "payment_status",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/congres-app_backend_pkg_utils.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/congres-app_backend_pkg_utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/soumissions": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retourne la liste paginée de toutes les soumissions avec filtres optionnels",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Lister toutes les soumissions (admin)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Recherche par titre, auteur, thème ou sujet",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filtrer par type (Abstract, Poster, Communication)",
                        "name": "type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filtrer par statut (En attente, Approuvée, Rejetée)",
                        "name": "statut",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Numéro de page (défaut: 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Nombre d'éléments par page (défaut: 10)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/congres-app_backend_pkg_utils.PaginatedResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/congres-app_backend_internal_models.Soumission"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/congres-app_backend_pkg_utils.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/congres-app_backend_pkg_utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/soumissions/export/csv": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Exporte la liste des soumissions au format CSV avec filtres optionnels",
                "produces": [
                    "text/csv"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Exporter les soumissions en CSV",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Recherche",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filtrer par type",
                        "name": "type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filtrer par statut",
                        "name": "statut",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/congres-app_backend_pkg_utils.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/congres-app_backend_pkg_utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/soumissions/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retourne les détails d'une soumission avec les informations de l'utilisateur",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Récupérer une soumission (admin)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID de la soumission",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/congres-app_backend_pkg_utils.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/congres-app_backend_internal_models.Soumission"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/congres-app_backend_pkg_utils.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/congres-app_backend_pkg_utils.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/congres-app_backend_pkg_utils.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/congres-app_backend_pkg_utils.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Supprime une soumission et son fichier associé",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Supprimer une soumission (admin)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID de la soumission",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/congres-app_backend_pkg_utils.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object",
                                            "properties": {
                                                "message": {
                                                    "type": "string"
                                                }
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/congres-app_backend_pkg_utils.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/congres-app_backend_pkg_utils.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/congres-app_backend_pkg_utils.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/congres-app_backend_pkg_utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/soumissions/{id}/approve": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Approuve une soumission et notifie l'utilisateur par email",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Approuver une soumission",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID de la soumission",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/congres-app_backend_pkg_utils.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/congres-app_backend_internal_models.Soumission"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/congres-app_backend_pkg_utils.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/congres-app_backend_pkg_utils.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/congres-app_backend_pkg_utils.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/congres-app_backend_pkg_utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/soumissions/{id}/download": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Télécharge le fichier PDF associé à une soumission",
                "produces": [
                    "application/pdf"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Télécharger le fichier d'une soumission",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID de la soumission",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/congres-app_backend_pkg_utils.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/congres-app_backend_pkg_utils.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/congres-app_backend_pkg_utils.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/congres-app_backend_pkg_utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/soumissions/{id}/reject": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Rejette une soumission avec une raison et notifie l'utilisateur par email",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Rejeter une soumission",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID de la soumission",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Raison du rejet",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.RejectRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/congres-app_backend_pkg_utils.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/congres-app_backend_internal_models.Soumission"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/congres-app_backend_pkg_utils.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/congres-app_backend_pkg_utils.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/congres-app_backend_pkg_utils.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/congres-app_backend_pkg_utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/stats": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retourne les statistiques globales des soumissions et inscriptions",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Obtenir les statistiques",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/congres-app_backend_pkg_utils.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/internal_handlers.StatsResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/congres-app_backend_pkg_utils.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/congres-app_backend_pkg_utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/users": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retourne la liste paginée de tous les utilisateurs avec recherche optionnelle",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Lister les utilisateurs (admin)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Recherche par nom, prénom, email ou téléphone",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Numéro de page (défaut: 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Nombre d'éléments par page (défaut: 10)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/congres-app_backend_pkg_utils.PaginatedResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/congres-app_backend_internal_models.User"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/congres-app_backend_pkg_utils.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/congres-app_backend_pkg_utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/users/{id}/deactivate": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Bascule le statut actif d'un utilisateur (activation/désactivation)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Activer/Désactiver un utilisateur",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID de l'utilisateur",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/congres-app_backend_pkg_utils.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object",
                                            "properties": {
                                                "message": {
                                                    "type": "string"
                                                },
                                                "user": {
                                                    "$ref": "#/definitions/congres-app_backend_internal_models.User"
                                                }
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/congres-app_backend_pkg_utils.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/congres-app_backend_pkg_utils.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/congres-app_backend_pkg_utils.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/congres-app_backend_pkg_utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "description": "Authentifie un utilisateur avec email et mot de passe et retourne les tokens d'accès",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Connexion utilisateur",
                "parameters": [
                    {
                        "description": "Identifiants de connexion",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/congres-app_backend_pkg_utils.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/internal_handlers.AuthResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/congres-app_backend_pkg_utils.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/congres-app_backend_pkg_utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/refresh": {
            "post": {
                "description": "Génère un nouveau token d'accès à partir d'un refresh token valide",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Rafraîchir le token d'accès",
                "parameters": [
                    {
                        "description": "Refresh token",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.RefreshRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/congres-app_backend_pkg_utils.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object",
                                            "properties": {
                                                "access_token": {
                                                    "type": "string"
                                                },
                                                "refresh_token": {
                                                    "type": "string"
                                                }
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/congres-app_backend_pkg_utils.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/congres-app_backend_pkg_utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "Crée un nouveau compte utilisateur avec les informations fournies et retourne les tokens d'accès",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Inscription d'un nouvel utilisateur",
                "parameters": [
                    {
                        "description": "Informations d'inscription",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/congres-app_backend_pkg_utils.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/internal_handlers.AuthResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/congres-app_backend_pkg_utils.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/congres-app_backend_pkg_utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/inscriptions": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Inscrit un utilisateur au congrès avec paiement via Orange Money",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "inscriptions"
                ],
                "summary": "Créer une inscription",
                "parameters": [
                    {
                        "description": "Informations d'inscription",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.CreateInscriptionRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/congres-app_backend_pkg_utils.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/congres-app_backend_internal_models.Inscription"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/congres-app_backend_pkg_utils.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/congres-app_backend_pkg_utils.ErrorResponse"
                        }
                    },
                    "402": {
                        "description": "Payment Required",
                        "schema": {
                            "$ref": "#/definitions/congres-app_backend_pkg_utils.ErrorResponse"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/congres-app_backend_pkg_utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/notifications": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retourne la liste paginée des notifications de l'utilisateur connecté",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "notifications"
                ],
                "summary": "Lister les notifications",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Numéro de page (défaut: 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Nombre d'éléments par page (défaut: 20)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/congres-app_backend_pkg_utils.PaginatedResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/congres-app_backend_internal_models.Notification"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/congres-app_backend_pkg_utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/notifications/read-all": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Marque toutes les notifications non lues de l'utilisateur connecté comme lues",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "notifications"
                ],
                "summary": "Marquer toutes les notifications comme lues",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/congres-app_backend_pkg_utils.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object",
                                            "properties": {
                                                "message": {
                                                    "type": "string"
                                                }
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/congres-app_backend_pkg_utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/notifications/unread-count": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retourne le nombre de notifications non lues de l'utilisateur connecté",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "notifications"
                ],
                "summary": "Nombre de notifications non lues",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/congres-app_backend_pkg_utils.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object",
                                            "properties": {
                                                "count": {
                                                    "type": "integer"
                                                }
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/congres-app_backend_pkg_utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/notifications/{id}/read": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Marque une notification spécifique comme lue pour l'utilisateur connecté",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "notifications"
                ],
                "summary": "Marquer une notification comme lue",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID de la notification",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/congres-app_backend_pkg_utils.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/congres-app_backend_internal_models.Notification"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/congres-app_backend_pkg_utils.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/congres-app_backend_pkg_utils.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/congres-app_backend_pkg_utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/profile": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retourne les informations du profil de l'utilisateur connecté",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "profile"
                ],
                "summary": "Récupérer le profil utilisateur",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/congres-app_backend_pkg_utils.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/congres-app_backend_internal_models.User"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/congres-app_backend_pkg_utils.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/congres-app_backend_pkg_utils.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Supprime définitivement le compte de l'utilisateur connecté ainsi que ses données associées",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "profile"
                ],
                "summary": "Supprimer le compte utilisateur",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/congres-app_backend_pkg_utils.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object",
                                            "properties": {
                                                "message": {
                                                    "type": "string"
                                                }
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/congres-app_backend_pkg_utils.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/congres-app_backend_pkg_utils.ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Modifie les informations du profil de l'utilisateur connecté",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "profile"
                ],
                "summary": "Mettre à jour le profil utilisateur",
                "parameters": [
                    {
                        "description": "Informations du profil à mettre à jour",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.UpdateProfileRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/congres-app_backend_pkg_utils.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/congres-app_backend_internal_models.User"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/congres-app_backend_pkg_utils.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/congres-app_backend_pkg_utils.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/congres-app_backend_pkg_utils.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/congres-app_backend_pkg_utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/profile/password": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Permet à l'utilisateur connecté de modifier son mot de passe",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "profile"
                ],
                "summary": "Changer le mot de passe",
                "parameters": [
                    {
                        "description": "Ancien et nouveau mot de passe",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.ChangePasswordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/congres-app_backend_pkg_utils.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object",
                                            "properties": {
                                                "message": {
                                                    "type": "string"
                                                }
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/congres-app_backend_pkg_utils.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/congres-app_backend_pkg_utils.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/congres-app_backend_pkg_utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/soumissions": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retourne la liste des soumissions de l'utilisateur connecté, triées par date de création",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "soumissions"
                ],
                "summary": "Lister les soumissions de l'utilisateur",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/congres-app_backend_pkg_utils.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/congres-app_backend_internal_models.Soumission"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/congres-app_backend_pkg_utils.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Soumet un document (PDF) avec les métadonnées associées pour un congrès",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "soumissions"
                ],
                "summary": "Créer une nouvelle soumission",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Type de soumission (Abstract, Poster, Communication)",
                        "name": "submission_type",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Thème",
                        "name": "theme",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Sujets",
                        "name": "topics",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Titre du document",
                        "name": "document_title",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Nom de l'auteur",
                        "name": "author_name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Résumé",
                        "name": "resume",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Mots-clés (JSON array ou séparés par des virgules)",
                        "name": "keywords",
                        "in": "formData"
                    },
                    {
                        "type": "file",
                        "description": "Fichier PDF",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/congres-app_backend_pkg_utils.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/congres-app_backend_internal_models.Soumission"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/congres-app_backend_pkg_utils.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/congres-app_backend_pkg_utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/soumissions/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retourne les détails d'une soumission spécifique de l'utilisateur connecté",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "soumissions"
                ],
                "summary": "Récupérer une soumission",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID de la soumission",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/congres-app_backend_pkg_utils.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/congres-app_backend_internal_models.Soumission"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/congres-app_backend_pkg_utils.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/congres-app_backend_pkg_utils.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/congres-app_backend_pkg_utils.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Supprime une soumission de l'utilisateur connecté et son fichier associé",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "soumissions"
                ],
                "summary": "Supprimer une soumission",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID de la soumission",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/congres-app_backend_pkg_utils.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object",
                                            "properties": {
                                                "message": {
                                                    "type": "string"
                                                }
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/congres-app_backend_pkg_utils.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/congres-app_backend_pkg_utils.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/congres-app_backend_pkg_utils.ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Met à jour les informations et/ou le fichier d'une soumission en attente",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "soumissions"
                ],
                "summary": "Modifier une soumission",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID de la soumission",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Type de soumission (Abstract, Poster, Communication)",
                        "name": "submission_type",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Thème",
                        "name": "theme",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Sujets",
                        "name": "topics",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Titre du document",
                        "name": "document_title",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Nom de l'auteur",
                        "name": "author_name",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Résumé",
                        "name": "resume",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Mots-clés",
                        "name": "keywords",
                        "in": "formData"
                    },
                    {
                        "type": "file",
                        "description": "Nouveau fichier PDF",
                        "name": "file",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/congres-app_backend_pkg_utils.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/congres-app_backend_internal_models.Soumission"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/congres-app_backend_pkg_utils.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/congres-app_backend_pkg_utils.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/congres-app_backend_pkg_utils.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/congres-app_backend_pkg_utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/webhooks/orange-money": {
            "post": {
                "description": "Reçoit les notifications de paiement Orange Money pour les inscriptions",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "webhooks"
                ],
                "summary": "Webhook Orange Money",
                "parameters": [
                    {
                        "description": "Payload du webhook Orange Money",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.orangeMoneyWebhookPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/congres-app_backend_pkg_utils.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object",
                                            "properties": {
                                                "status": {
                                                    "type": "string"
                                                }
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/congres-app_backend_pkg_utils.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/congres-app_backend_pkg_utils.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/congres-app_backend_pkg_utils.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "congres-app_backend_internal_models.Inscription": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "methode_paiement": {
                    "type": "string"
                },
                "montant": {
                    "type": "number"
                },
                "nom": {
                    "type": "string"
                },
                "numero_facture": {
                    "type": "string"
                },
                "organisme": {
                    "type": "string"
                },
                "participation_type": {
                    "type": "string"
                },
                "payment_status": {
                    "type": "string"
                },
                "pays": {
                    "type": "string"
                },
                "prenom": {
                    "type": "string"
                },
                "telephone": {
                    "type": "string"
                },
                "transaction_id": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "congres-app_backend_internal_models.Notification": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "id": {
                    "type": "string"
                },
                "notifiable_id": {
                    "type": "string"
                },
                "notifiable_type": {
                    "type": "string"
                },
                "read_at": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "congres-app_backend_internal_models.Soumission": {
            "type": "object",
            "properties": {
                "author_name": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "document_title": {
                    "type": "string"
                },
                "file_path": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "keywords": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "raison_rejet": {
                    "type": "string"
                },
                "resume": {
                    "type": "string"
                },
                "statut": {
                    "description": "En attente, Approuvée, Rejetée",
                    "type": "string"
                },
                "submission_type": {
                    "description": "Abstract, Poster, Communication",
                    "type": "string"
                },
                "theme": {
                    "type": "string"
                },
                "topics": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/congres-app_backend_internal_models.User"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "congres-app_backend_internal_models.User": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "adresse": {
                    "type": "string"
                },
                "biographie": {
                    "type": "string"
                },
                "civilite": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "nom": {
                    "type": "string"
                },
                "notifications": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/congres-app_backend_internal_models.Notification"
                    }
                },
                "organisme": {
                    "type": "string"
                },
                "prenom": {
                    "type": "string"
                },
                "profession": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "sexe": {
                    "type": "string"
                },
                "soumissions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/congres-app_backend_internal_models.Soumission"
                    }
                },
                "telephone": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "congres-app_backend_pkg_utils.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "congres-app_backend_pkg_utils.PaginatedResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "limit": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "success": {
                    "type": "boolean"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "congres-app_backend_pkg_utils.SuccessResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "success": {
                    "type": "boolean"
                }
            }
        },
        "internal_handlers.AuthResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "refresh_token": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/congres-app_backend_internal_models.User"
                }
            }
        },
        "internal_handlers.ChangePasswordRequest": {
            "type": "object",
            "required": [
                "current_password",
                "new_password"
            ],
            "properties": {
                "current_password": {
                    "type": "string"
                },
                "new_password": {
                    "type": "string",
                    "minLength": 6
                }
            }
        },
        "internal_handlers.CreateInscriptionRequest": {
            "type": "object",
            "required": [
                "code_otp",
                "email",
                "methode_paiement",
                "montant",
                "nom",
                "participation_type",
                "pays",
                "prenom",
                "telephone"
            ],
            "properties": {
                "code_otp": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "methode_paiement": {
                    "type": "string"
                },
                "montant": {
                    "type": "number"
                },
                "nom": {
                    "type": "string"
                },
                "organisme": {
                    "type": "string"
                },
                "participation_type": {
                    "type": "string"
                },
                "pays": {
                    "type": "string"
                },
                "prenom": {
                    "type": "string"
                },
                "telephone": {
                    "type": "string"
                }
            }
        },
        "internal_handlers.LoginRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "internal_handlers.RefreshRequest": {
            "type": "object",
            "required": [
                "refresh_token"
            ],
            "properties": {
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "internal_handlers.RegisterRequest": {
            "type": "object",
            "required": [
                "civilite",
                "email",
                "nom",
                "password",
                "prenom",
                "sexe",
                "telephone"
            ],
            "properties": {
                "adresse": {
                    "type": "string"
                },
                "biographie": {
                    "type": "string"
                },
                "civilite": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "nom": {
                    "type": "string"
                },
                "organisme": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "minLength": 6
                },
                "prenom": {
                    "type": "string"
                },
                "profession": {
                    "type": "string"
                },
                "sexe": {
                    "type": "string"
                },
                "telephone": {
                    "type": "string"
                }
            }
        },
        "internal_handlers.RejectRequest": {
            "type": "object",
            "required": [
                "raison"
            ],
            "properties": {
                "raison": {
                    "type": "string"
                }
            }
        },
        "internal_handlers.StatsResponse": {
            "type": "object",
            "properties": {
                "approuvees": {
                    "type": "integer"
                },
                "en_attente": {
                    "type": "integer"
                },
                "inscriptions_confirmees": {
                    "type": "integer"
                },
                "inscriptions_en_attente": {
                    "type": "integer"
                },
                "inscriptions_en_ligne": {
                    "type": "integer"
                },
                "inscriptions_presentiel": {
                    "type": "integer"
                },
                "inscriptions_virtuel": {
                    "type": "integer"
                },
                "rejetees": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                },
                "total_articles": {
                    "type": "integer"
                },
                "total_communications": {
                    "type": "integer"
                },
                "total_inscriptions": {
                    "type": "integer"
                },
                "total_posters": {
                    "type": "integer"
                }
            }
        },
        "internal_handlers.UpdateProfileRequest": {
            "type": "object",
            "properties": {
                "adresse": {
                    "type": "string"
                },
                "biographie": {
                    "type": "string"
                },
                "civilite": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "nom": {
                    "type": "string"
                },
                "organisme": {
                    "type": "string"
                },
                "prenom": {
                    "type": "string"
                },
                "profession": {
                    "type": "string"
                },
                "sexe": {
                    "type": "string"
                },
                "telephone": {
                    "type": "string"
                }
            }
        },
        "internal_handlers.orangeMoneyWebhookPayload": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "string"
                },
                "order_id": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "signature": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "transaction_id": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Bearer JWT token",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Congrès API",
	Description:      "API de gestion des congrès, soumissions et inscriptions",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
